# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0003_foto_image_resized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
