# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_auto_20161020_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='/Users/dani2/Downloads/practica_Python_Django_Avanzado/media/'),
        ),
    ]
